# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sign_Up(object):
    def setupUi(self, Sign_Up):
        Sign_Up.setObjectName("Sign_Up")
        Sign_Up.resize(556, 656)
        font = QtGui.QFont()
        font.setFamily("Arial")
        Sign_Up.setFont(font)
        self.SignUp = QtWidgets.QLabel(Sign_Up)
        self.SignUp.setGeometry(QtCore.QRect(230, 20, 131, 61))
        font.setPointSize(20)
        self.SignUp.setFont(font)
        self.SignUp.setObjectName("SignUp")
        font.setPointSize(14)
        self.StudentNameLabel = QtWidgets.QLabel(Sign_Up)
        self.StudentNameLabel.setGeometry(QtCore.QRect(40, 100, 161, 41))
        self.StudentNameLabel.setFont(font)
        self.StudentNameLabel.setObjectName("StudentNameLabel")
        self.textStudentName = QtWidgets.QTextEdit(Sign_Up)
        self.textStudentName.setGeometry(QtCore.QRect(40, 140, 471, 51))
        self.textStudentName.setFont(font)
        self.textStudentName.setObjectName("textStudentName")
        self.textPassword = QtWidgets.QTextEdit(Sign_Up)
        self.textPassword.setGeometry(QtCore.QRect(40, 250, 471, 51))
        self.textPassword.setFont(font)
        self.textPassword.setObjectName("textPassword")
        self.PasswordLabel = QtWidgets.QLabel(Sign_Up)
        self.PasswordLabel.setGeometry(QtCore.QRect(40, 210, 111, 31))
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.SignUpButton = QtWidgets.QPushButton(Sign_Up)
        self.SignUpButton.setGeometry(QtCore.QRect(40, 580, 471, 51))
        self.SignUpButton.setFont(font)
        self.SignUpButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 85, 255);")
        self.SignUpButton.setObjectName("SignUpButton")
        self.CheckPasswordLabel = QtWidgets.QLabel(Sign_Up)
        self.CheckPasswordLabel.setGeometry(QtCore.QRect(40, 320, 221, 31))
        self.CheckPasswordLabel.setFont(font)
        self.CheckPasswordLabel.setObjectName("CheckPasswordLabel")
        self.textPasswordCheck = QtWidgets.QTextEdit(Sign_Up)
        self.textPasswordCheck.setGeometry(QtCore.QRect(40, 360, 471, 51))
        self.textPasswordCheck.setFont(font)
        self.textPasswordCheck.setObjectName("textPasswordCheck")
        self.WalletPasswordLabel = QtWidgets.QLabel(Sign_Up)
        self.WalletPasswordLabel.setGeometry(QtCore.QRect(40, 430, 271, 31))
        self.WalletPasswordLabel.setFont(font)
        self.WalletPasswordLabel.setObjectName("WalletPasswordLabel")
        self.textWalletPassword = QtWidgets.QTextEdit(Sign_Up)
        self.textWalletPassword.setGeometry(QtCore.QRect(40, 470, 471, 51))
        self.textWalletPassword.setFont(font)
        self.textWalletPassword.setObjectName("textWalletPassword")

        self.retranslateUi(Sign_Up)
        QtCore.QMetaObject.connectSlotsByName(Sign_Up)

    def retranslateUi(self, Sign_Up):
        _translate = QtCore.QCoreApplication.translate
        Sign_Up.setWindowTitle(_translate("Sign_Up", "Form"))
        self.SignUp.setText(_translate("Sign_Up", "Sign Up"))
        self.StudentNameLabel.setText(_translate("Sign_Up", "Student Name"))
        self.PasswordLabel.setText(_translate("Sign_Up", "Password"))
        self.SignUpButton.setText(_translate("Sign_Up", "Login"))
        self.CheckPasswordLabel.setText(_translate("Sign_Up", "Check password"))
        self.WalletPasswordLabel.setText(_translate("Sign_Up", "User wallet private key"))

    def returnStudentInfo(self):
        return self.textStudentName.toPlainText(), self.textPassword.toPlainText(), self.textPasswordCheck.toPlainText(), self.textWalletPassword.toPlainText()
    
    def reset(self):
        self.textStudentName.setText("")
        self.textPassword.setText("")
        self.textPasswordCheck.setText("")
        self.textWalletPassword.setText("")